stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw-data
    - src/preprocess.py
    params:
    - preprocess.DATA_YEAR_START_PP
    - preprocess.HOW_IMPUTE_NAN
    - preprocess.TEST_START_PP
    - preprocess.VAL_START_PP
    outs:
    - data/preprocessed/train_preprocessed.csv
    - data/preprocessed/val_preprocessed.csv
    - data/preprocessed/test_preprocessed.csv
    - data/target/target_df.csv
  featurize:
    cmd: python src/featurize.py
    deps:
    - data/preprocessed/train_preprocessed.csv
    - data/preprocessed/val_preprocessed.csv
    - data/preprocessed/test_preprocessed.csv
    - src/featurize.py
    params:
    - featurize.BATCH_SIZE_PRO
    - featurize.WINDOW_SIZE_PRO
    - featurize.SUFFLE_BUFFER_PRO
    - featurize.TARGET_PERIOD_PRO
    - featurize.HOW_WINDOW_GEN_PRO
    outs:
    - data/featurized/train_processed
    - data/featurized/val_processed
    - data/featurized/test_processed
  train: 
    cmd: python src/train.py
    deps:
    - data/featurized/train_processed
    - data/featurized/val_processed
    - data/featurized/test_processed
    - src/train.py
    params:
    - train.EPOCHS
    - train.PATIENCE
    - train.NEURONS
    - train.MODEL_NAME
    outs:
    - src/model/model_train.h5
    - evaluation/history.json
    - evaluation/history_params.json
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - src/model/model_train.h5
    - data/target/target_df.csv
    - evaluation/history.json
    outs:
    - evaluation/learning_curves.png
    - evaluation/metrics_semana.png
    - evaluation/prediction_series.png
    - evaluation/residuo.png
  
