stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw-data
    - src/preprocess.py
    params:
    - preprocess.DATA_YEAR_START_PP
    - preprocess.HOW_IMPUTE_NAN
    - preprocess.TEST_START_PP
    - preprocess.VAL_START_PP
    outs:
    - data/preprocessed
    - data/target/target_df.csv
  featurize:
    cmd: python src/featurize.py
    deps:
    - data/preprocessed
    - src/featurize.py
    params:
    - featurize.BATCH_SIZE_PRO
    - featurize.WINDOW_SIZE_PRO
    - featurize.SUFFLE_BUFFER_PRO
    - featurize.TARGET_PERIOD_PRO
    - featurize.HOW_WINDOW_GEN_PRO
    outs:
    - data/featurized
  train: 
    cmd: python src/train.py
    deps:
    - data/featurized
    - data/target/target_df.csv
    - src/train.py
    params:
    - train.EPOCHS
    - train.PATIENCE
    - train.NEURONS
    - train.MODEL_NAME
    outs:
    - src/model
    - src/valuation
  
