stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw-data
    - src/preprocess.py
    params:
    - preprocess.DATA_YEAR_START_PP
    - preprocess.HOW_IMPUTE_NAN
    - preprocess.TEST_START_PP
    - preprocess.VAL_START_PP
    outs:
    - data/preprocessed
  featurize:
    cmd: python src/featurize.py
    deps:
    - data/preprocessed
    - src/featurize.py
    params:
    - featurize.BATCH_SIZE_PRO
    - featurized.WINDOW_SIZE_PRO
    - featurized.SUFFLE_BUFFER_PRO
    - featurized.TARGET_PERIOD_PRO
    - featurized.HOW_WINDOW_GEN_PRO
    outs:
    - data/featurized

