preprocess:
  DATA_YEAR_START_PP: 2012
  VAL_START_PP: '2019-03-01'
  TEST_START_PP: '2021-03-12'
  HOW_IMPUTE_NAN: 'sazonalidade'

featurize:
  BATCH_SIZE_PRO: 32
  WINDOW_SIZE: 7
  SUFFLE_BUFFER_PRO: 20
  TARGET_PERIOD: 1
  HOW_INPUT_WINDOW_GEN: weekly
  HOW_TARGET_WINDOW_GEN: weekly

train:
  EPOCHS: 150
  PATIENCE: 8
  NEURONS: [8]
  MODEL_NAME: 'model_train.h5'

evaluate:
  AUTOREGRESSIVE_STEPS: 5
  MODEL_TYPE: 'AUTOREGRESSIVE'