preprocess:
  DATA_YEAR_START_PP: 2012
  VAL_START_PP: '2019-03-01'
  TEST_START_PP:
  TEST_START_FIXED: '2021-03-12'
  HOW_IMPUTE_NAN: sazonalidade

featurize:
  BATCH_SIZE_PRO: 64
  WINDOW_SIZE: 60
  SUFFLE_BUFFER_PRO: 20
  TARGET_PERIOD: 5
  HOW_INPUT_WINDOW_GEN: weekly
  HOW_TARGET_WINDOW_GEN: weekly
  MODEL_TYPE: AUTOREGRESSIVE

train:
  EPOCHS: 200
  PATIENCE: 10
  NEURONS:
  - 128
  - 32
  LAYERS:
  - RNN
  - RNN
  MODEL_NAME: model_train
  LEARNING_RATE: 0.001
