preprocess:
  DATA_YEAR_START_PP: 2012
  VAL_START_PP: '2019-03-01'
  TEST_START_PP: '2021-03-12'
  HOW_IMPUTE_NAN: 'sazonalidade'

featurize:
  BATCH_SIZE_PRO: 32
  WINDOW_SIZE_PRO: 35
  SUFFLE_BUFFER_PRO: 20
  TARGET_PERIOD_PRO: 1
  HOW_WINDOW_GEN_PRO: 'autorregressivo'

train:
  EPOCHS: 150
  PATIENCE: 30
  NEURONS: [32]
  MODEL_NAME: 'model_train.h5'